include_dirs:
    - include
source_dirs:
    - src
links:
options:
    - --std=c++17
    - -O3
    - -pthread
    - -fopenmp
builddir: builddir
runs:
  dummy: dummy-data.bin dummy-queries.bin
  contest-1m: contest-data-release-1m.bin contest-queries-release-1m.bin
  contest-10m: contest-data-release-10m.bin contest-queries-release-10m.bin
